services:
  api-gateway:
    image: tedymoisa/micro-link-shortner/api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DATABASE_URL: postgres://user:pass@dbhost:5432/db
      NODE_ENV: development
    mem_limit: 512m
    cpus: 0.5
    restart: unless-stopped
