services:
  postgres:
    image: postgres:16
    container_name: micro-link-shortener-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 10s
      timeout: 5s
      retries: 5
    mem_limit: 512m
    cpus: 0.5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: micro-link-shortener-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass

  redis:
    image: redis:8-alpine
    container_name: micro-link-shortener-redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: pass
    command: ["redis-server", "--requirepass", "pass"]
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
